@ECHO OFF
ECHO ..............................................................................................
ECHO :                  Welcome to the RP1210.py automatic-ish test suite!                        :
ECHO ..............................................................................................
@REM ECHO Preparing...
@REM REM ECHO Checking pytest installation...
@REM REM py -m pip install -U -q pytest
@REM REM py -m pip install -U -q pytest-cov
@REM ECHO Preparing test directory...
@REM ECHO Removing old source code from Test directory...
@REM rmdir /s /q Test\RP1210
@REM ECHO Copying source code into Test directory...
@REM xcopy /v /s /y /q RP1210 Test\RP1210\
@REM ECHO Done!
@REM ECHO ..............................................................................................
ECHO Disconnect all RP1210 adapters before continuing.
@REM pause
python -m pytest -l -v -ra --tb=long --cov=RP1210 --cov-branch --cov-report term-missing
ECHO Done
pause
